name: release

env:
  go-version: '^1.22.0'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-and-check-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run tests
        uses: ngergs/composite-actions/go-test@main
        with:
          go-version: ${{ env.go-version }}
      - name: Check for release
        id: semrel
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      is-release: ${{ steps.semrel.outputs.releases_created }}
      version: ${{ steps.semrel.outputs.tag_name }}
  release:
    needs: test-and-check-release
    if: needs.test-and-check-release.outputs.is-release == 'true'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ngergs/composite-actions/go-release@main
        with:
          go-version: ${{ env.go-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
