name: release

env:
  go-version: '^1.20.3'

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-and-pre-release:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: ngergs/composite-actions/go-test@main
        with:
          go-version: ${{ env.go-version }}
      - name: Determine release
        uses:  ngergs/composite-actions/prepare-semantic-release@main
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-emojis: true
    outputs:
      version: ${{ steps.semrel.outputs.version }}
      release-notes-cache-key: ${{ steps.semrel.outputs.release-notes-cache-key }}
  release:
    needs: test-and-pre-release
    if: needs.test-and-pre-release.outputs.version != ''
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-os:
          - 'darwin'
          - 'linux'
          - 'windows'
        go-arch:
          - 'amd64'
    steps:
      - name: Release go binary
        uses: ngergs/composite-actions/release-go-binary@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          binary-name: websrv
          go-version: ${{ env.go-version }}
          go-os: ${{ matrix.go-os }}
          go-arch: ${{ matrix.go-arch }}
          release-version: ${{ needs.test-and-pre-release.outputs.version }}
          release-notes-cache-key: ${{ needs.test-and-pre-release.outputs.release-notes-cache-key }}
          go-build-path: "./cmd/websrv/"
      - name: Prepare licenses
        if: ${{ matrix.go-os == 'linux' && matrix.go-arch == 'amd64' }}
        shell: bash
        run: |
          go install github.com/google/go-licenses@latest && \
          $(go env GOPATH)/bin/go-licenses save ./... --save_path=legal
      - name: Release docker
        if: ${{ matrix.go-os == 'linux' && matrix.go-arch == 'amd64' }}
        uses: ngergs/composite-actions/release-docker@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-checkout: false
          docker-image-name: websrv
          dockerhub-username:  ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          release-version: ${{ needs.test-and-pre-release.outputs.version }}
          release-notes-cache-key: ${{ needs.test-and-pre-release.outputs.release-notes-cache-key }}
          dockerfile: build/Dockerfile
